### ISSUE TITLE
question: How to tag?

### ISSUE THREAD

**Issue by marioidival** [tjson/tjson-ruby#6]
In spec, only keys are tagged, but in your lib values are too. What is correct?

_p.s: 'm writing a Python Version_

**Comment by tarcieri** [comment]
The latest spec is correct: the lib is out of date.

I'm in the process of rewriting the code for this version.

**Comment by marioidival** [comment]
@tarcieri Ok, thanks!

**Comment by tarcieri** [comment]
See #5 (WIP)
